---
title: "DS Final Project"
author: "Neha Anand, John Morkos, Zach Murphy, Thomas Le"
date: "5/18/2021"
output:  flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading data, echo=FALSE, message=FALSE}
library(tidyverse)
library(ggplot2)
library(plotly)
library(datasets)
library(shinyWidgets)
vaccines = read_csv("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/us_state_vaccinations.csv")

cases = read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv")

cases_clean = cases %>% pivot_longer(names_to="Date", values_to="Cases", cols=colnames(cases[12:length(cases)]))
cases_clean = cases_clean %>% mutate(Date = as.Date(cases_clean$Date, format ="%m/%d/%y"))

deaths = read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv")
deaths_clean = deaths %>% pivot_longer(names_to="Date", values_to="Cases", cols=colnames(deaths[13:length(deaths)]))
deaths_clean = deaths_clean %>% mutate(Date = as.Date(deaths_clean$Date, format ="%m/%d/%y"))

vaccines = vaccines %>% mutate(share_doses_used=share_doses_used*100)


```


Heat Map 
======================
Sidebar {.sidebar}
----------------------------------
### Select Inputs
```{r input1, echo=FALSE, message=FALSE}

varSelectInput("vaccine_trend_1", "Select vaccination trend", vaccines[3: length(vaccines)])

selectInput("google_trends_1", "Select a google search term", c("covid", "vaccine", "vaccine near me", "mask", "social distancing", "qanon"))



```

Heat Map
-------------------------------------
### Heat Map
```{r rendering heat map, echo=FALSE}




```


Graphs of Trends 
======================

Sidebar {.sidebar}
---------------------------------------------
### Select Inputs
```{r input2, echo=FALSE, message=FALSE}
varSelectInput("vaccine_trend_2", "Select vaccination trend", vaccines[3: length(vaccines)])

selectInput("google_trends_2", "Select a google search term", c("covid", "vaccine", "vaccine near me", "mask", "social distancing", "qanon"))

checkboxInput("smooth", "Check to add smoothed time series")

states = c("All", state.name)

prettyCheckboxGroup("states", "Select state(s)", states, shape="square", selected="All", icon=icon("check"))
```

Column {data-width = 1000}
-------------------------------------------

### Vaccination Trends
```{r rendering vaccination plot, echo=FALSE}
  renderPlotly({
  if(length(input$states)!=0){
    if(input$states!="All"){
      graph_data=vaccines%>%filter(location%in%input$states)}
    else{
      graph_data=vaccines
    }
    
    
    
    plot = ggplot(data = graph_data, aes_string(x="date", y=input$vaccine_trend_2, fill="location")) + geom_point(aes(color=location))
    plot = plot + theme(axis.text.x=element_text(angle=45, size = 10)) + ggtitle(as.character(input$vaccine_trend_2))
   if(input$smooth){
      plot = plot+geom_smooth(aes(color=location))
    }
   
    }
    else
    {
       graph_data=vaccines
      plot = ggplot(data = graph_data, aes_string(x="date", y=input$vaccine_trend_2))
    }

 ggplotly(plot)
})
```

### Google Search Trend
```{r rendering google trends plot, echo=FALSE, message=FALSE}

renderPlotly({
  
  if(input$google_trends_2=="covid"){
    googtrend = read_csv("https://raw.githubusercontent.com/nanand7/DS-Project-2021/main/Google%20Trends%20Data/covid%20data.csv")
  }
  else if(input$google_trends_2=="vaccine"){
    googtrend = read_csv("https://raw.githubusercontent.com/nanand7/DS-Project-2021/main/Google%20Trends%20Data/vaccine%20data.csv")
  }
   else if(input$google_trends_2=="vaccine near me"){
    googtrend = read_csv("https://raw.githubusercontent.com/nanand7/DS-Project-2021/main/Google%20Trends%20Data/vaccine%20near%20me%20data.csv")
   }
   else if(input$google_trends_2=="mask"){
    googtrend = read_csv("https://raw.githubusercontent.com/nanand7/DS-Project-2021/main/Google%20Trends%20Data/mask%20data.csv")
   }
    else if(input$google_trends_2=="social distancing"){
    googtrend = read_csv("https://raw.githubusercontent.com/nanand7/DS-Project-2021/main/Google%20Trends%20Data/social%20distancing%20data.csv")
   }
   else if(input$google_trends_2=="qanon"){
    googtrend = read_csv("https://raw.githubusercontent.com/nanand7/DS-Project-2021/main/Google%20Trends%20Data/qanon%20data.csv")
    googtrend$hits = as.numeric(googtrend$hits)
   }
  
  
   if(length(input$states)!=0){
    if(input$states!="All"){
      graph_data_goog=googtrend%>%filter(geo %in% input$states)
      }
    else{
      graph_data_goog=googtrend
    }
    
    plot2 = ggplot(data = graph_data_goog, aes(x=date, y=hits, fill=geo)) + geom_point(aes(color=geo))
    plot2 = plot2 + theme(axis.text.x=element_text(angle=45, size = 10)) + ggtitle(as.character(input$google_trends_2))
    
   if(input$smooth){
      plot2 = plot2+geom_smooth(aes(color=geo))
    }
   
    }
    else
    {
       graph_data_goog=googtrend
      plot2 = ggplot(data = graph_data_goog, aes(x=date, y=hits))
    }

 ggplotly(plot2)



})
```


Web App Details 
======================
### App Details 
Write details about final app here
Vaccination data from: Our World in Data - https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations 
Cases and deaths data from: COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University - https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series 
